### ISSUE TITLE
npm start，App.tsx报错

### ISSUE THREAD

**Issue by zhjgh** [nefe/kiwi#2]
(7,3): The class method 'changeLang' must be marked either 'private', 'public', or 'protected'

**Comment by linhuiw** [comment]
![image](https://user-images.githubusercontent.com/722603/52940079-a3f46e80-33a0-11e9-9a54-57ac2d370c52.png)

未复现这个报错，是使用 `yarn` 安装的依赖么？
推测是安装的 `node_modules` 版本问题
